services:
  api:
    build:
      context: ./SpotYnov API
    ports:
      - "3000:3000"
    volumes:
      - ./SpotYnov API:/usr/src/app
    environment:
      - NODE_ENV=development

  app:
    build:
      context: ./SpotYnov APP
    ports:
      - "5173:80" # Mapper le port 5173 vers 80 pour nginx
    depends_on:
      - api
